### PR TITLE
:art::green_apple: include other kingdoms as optional emits

### LINKED ISSUE #185: Should we include the other kingdoms so they are linked to the output? Some researchers may be interested in some of the other fasta files that could be generated
Should we include the other kingdoms so they are linked to the output? Some researchers may be interested in some of the other fasta files that could be generated

_Originally posted by @WiscEvan in https://github.com/KwanLab/Autometa/pull/157#r696988286_

In reference to:
https://github.com/KwanLab/Autometa/blob/a0e86ae3e79160de11ccd87cb2b83297c9656f7c/modules/local/split_kingdoms.nf

### PR DESCRIPTION
**Pull request by WiscEvan**
:art::green_apple: include other kingdoms as optional emits in `split_kingdoms.nf`

closes #185

### CODE REVIEW

**Comment by chasemc** [comment]
closes https://github.com/KwanLab/Autometa/issues/151

**Comment by chasemc** [comment]
@WiscEvan 
Does ["${meta.id}.taxonomy.tsv"](https://github.com/KwanLab/Autometa/blob/92179f561a1e4672fa4ab9b4ecd62f2a544c8e44/modules/local/split_kingdoms.nf#L27-L28)
contain all the kingdoms in it or is there a separate taxonomy per split?

**Comment by WiscEvan** [comment]
> @WiscEvan Does ["${meta.id}.taxonomy.tsv"](https://github.com/KwanLab/Autometa/blob/92179f561a1e4672fa4ab9b4ecd62f2a544c8e44/modules/local/split_kingdoms.nf#L27-L28) contain all the kingdoms in it or is there a separate taxonomy per split?

Yes, `taxonomy.tsv` contains all of the kingdoms that have been assigned a taxonomy

**Comment by chasemc** [comment]
@ajlail98 You mentioned in slack you were looking at this. I typed out a huge comment here but then exited the page so lost it. In short the fix will be a bit complicated (requires changes in multiple files). If you want we could meet and work through it together, or if you're too busy let me know and I'll start working on it soonish.

**Comment by WiscEvan** [comment]
This will be tackled in the `185-andrew-chase` branch

**Comment by chasemc** [comment]
Taking a look at this now. One thing @ajlail98 and I are doing is removing the hard-coding of taxons (e.g. "bacteria", "archaea")

@WiscEvan, this would change the emits in `process SPLIT_KINGDOMS` from:

https://github.com/KwanLab/Autometa/blob/36d52b18425d765a804a09f020bc2bda8374094c/modules/local/split_kingdoms.nf#L27-L30

to:
```
    output:
        tuple val(meta), path("${meta.id}.taxonomy.tsv"), emit: taxonomy
        tuple val(meta), path("${meta.id}.*.fna")       , emit: contigs_grouped_by_taxon // not kingdom specific, depends on --split-rank-and-write
        path  '*.version.txt'                           , emit: version
```
How do we feel about `contigs_grouped_by_taxon` as the emit name?

**Comment by chasemc** [comment]
Waiting for `nr` to redownload......
Alt text

**Comment by WiscEvan** [comment]
> Taking a look at this now. One thing @ajlail98 and I are doing is removing the hard-coding of taxons (e.g. "bacteria", "archaea")
> 
> @WiscEvan, this would change the emits in `process SPLIT_KINGDOMS` from:
> 
> https://github.com/KwanLab/Autometa/blob/36d52b18425d765a804a09f020bc2bda8374094c/modules/local/split_kingdoms.nf#L27-L30
> 
> to something like:
> 
> ```
>     output:
>         tuple val(meta), path("${meta.id}.taxonomy.tsv"), emit: taxonomy
>         tuple val(meta), path("${meta.id}.*.fna")       , emit: contigs_grouped_by_taxon // not kingdom specific, depends on --split-rank-and-write
>         path  '*.version.txt'                           , emit: version
> ```
> 
> How do we feel about `contigs_grouped_by_taxon` as the emit name?

✅ That sounds appropriate to me

**Pull request closed without merging**
