### PR TITLE
Change the URLs to github from bitbucket

### PR DESCRIPTION
**Pull request by hyphaltip**
Swap URLs to the new repo location

### CODE REVIEW

**Comment by jason-c-kwan** [comment]
Hi Jason - Thanks for spotting this! I think the checks are failing because we didn't implement readthedocs.org in Master yet - @WiscEvan this should be safe to merge, right?

**Comment by WiscEvan** [comment]
Yes, this is safe to merge. readthedocs is building off of the 2.0 release files.

**Comment by jason-c-kwan** [comment]
Also, turned out we had the old URL in the README.md file.

**Comment by WiscEvan** [comment]
It looks like you've found all of the old URLs:

```bash
(autometa) ➜  Autometa git:(master) ✗ grep -lr "bitbucket" .
./Dockerfile
grep: ./tests/dtc_data/metagenome.fna.gz: No such file or directory
./docs/build/html/_static/css/theme.css
./docs/build/html/_static/fonts/fontawesome-webfont.svg
./docs/build/html/_static/fonts/fontawesome-webfont.ttf
./docs/build/html/_static/fonts/fontawesome-webfont.eot
./LCA_README.md
./README.md
```

**Pull request merged**
