### PR TITLE
nr.gz database downloading bug

### PR DESCRIPTION
**Pull request by WiscEvan**
- Found an issue with `check_dbs` where autometa will loook for `nr.dmnd.md5` and if it is not found, will update nr. However, when nr is updated, the nr.dmnd.md5 is never written. 
- Fixed file path handling to be less arch specific 
- updated variables for readability.

### CODE REVIEW

**Comment by WiscEvan** [comment]
This has not been performance tested outside of running the script to see if any error messages were emitted.

**Comment by jason-c-kwan** [comment]
Do you at least know if the error is corrected? From looking through the code it seems to look for nr.gz.md5 now instead of nr.dmnd.md5. Is that correct?

**Comment by WiscEvan** [comment]
There exists an nr.gz checksum on NCBI's FTP server (See here [nr.gz.md5](https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz.md5) Where the diamond formatted database checksum is not hosted anywhere.

**Comment by jason-c-kwan** [comment]
OK, well after I merge, please check with the user that this fixes their problem.

**Pull request merged**
