### PR TITLE
Fix NA issues after Pandas update

### PR DESCRIPTION
**Pull request by chasemc**

### CODE REVIEW

**Comment by chasemc** [comment]
Related: https://github.com/KwanLab/Autometa/issues/349

**Comment by Sidduppal** [comment]
Looks good. Few points:
- Please implement the changes for hbscan as well.
- Update the version for the new release
- Is `dev` upto date with `main` I would do a pull before the merge.

**Comment by chasemc** [comment]
I've spent as much time as I can on this and welcome anyone else to make the changes mentioned above. I already fast forwarded dev onto main

**Comment by Sidduppal** [comment]
In reference to 
> With this update I'm getting more and better clusters than the unit test data t
hat I have access to (we're looking to that in the meantime).

I ran binning (using `dbscan`) using the `dev` branch and `v2.0.0` and the results are exactly the same. Files are attached for reference. I will do the same changes for `hdbscan`.

[Archive.zip](https://github.com/user-attachments/files/15840412/Archive.zip)

**Comment by chasemc** [comment]
Fixes #349

**Review by Sidduppal — APPROVED** [review]

**Pull request merged**
